on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/**"
      - "*.sh"
      - "patches/*.patch"

env:
  # version: m88
  skia_branch: chrome/m88
  skia_commit: 21ebdec5170d890bb7fc7ec88d3dc0ee9995e600
  release: m88-21ebdec517
  archive: true

jobs:

  macos:
    runs-on: macos-10.15
    strategy:
      matrix:
        build_type: [Release, Debug]
      fail-fast: false
    env:
      platform: macos
      build_type: ${{ matrix.build_type }}
    steps:
      - uses: actions/checkout@v2
      - run: ./check_release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ./build_macos.sh
      - uses: actions/upload-artifact@v2
        with:
          name: Skia-${{ env.release }}-macos-${{ matrix.build_type }}-x64.zip
          path: '*.zip'
      - run: ./release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux:
    runs-on: ubuntu-latest
    container: ubuntu:14.04
    strategy:
      matrix:
        build_type: [Release, Debug]
      fail-fast: false
    env:
      platform: linux
      build_type: ${{ matrix.build_type }}
    steps:
      - uses: actions/checkout@v2
      - run: sudo ./prepare_linux.sh
      - run: ./check_release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: PATH=/usr/lib/binutils-2.26/bin:$PATH ./build_linux.sh
      - uses: actions/upload-artifact@v2
        with:
          name: Skia-${{ env.release }}-linux-${{ matrix.build_type }}-x64.zip
          path: '*.zip'
      - run:  ./release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows:
    runs-on: windows-2019
    strategy:
      matrix:
        build_type: [Release, Debug]
      fail-fast: false
    env:
      platform: windows
      build_type: ${{ matrix.build_type }}
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: ./check_release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: microsoft/setup-msbuild@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - shell: bash
        run: ./build_windows.sh
      - uses: actions/upload-artifact@v2
        with:
          name: Skia-${{ env.release }}-windows-${{ matrix.build_type }}-x64.zip
          path: '*.zip'
      - shell: bash
        run: ./release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
